# Generated by Django 4.1.5 on 2023-01-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-timestamp']},
        ),
    ]
