# Generated by Django 4.1.5 on 2023-01-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalleventa_deposito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='cantidad',
            new_name='cantidadc',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidadp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comida'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
