# Generated by Django 4.1.5 on 2023-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comida_imagen_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='deposito',
            name='cantidadc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposito',
            name='cantidadp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposito',
            name='comida',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.comida'),
            preserve_default=False,
        ),
    ]
