# Generated by Django 4.1.5 on 2023-01-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_deposito_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='cantidadc',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidadc',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='comida',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
