# Generated by Django 4.1.5 on 2023-01-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria_remove_deposito_cantidadc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='can1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='can8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro1', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro2', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro3', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro4', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro5', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro6', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro7', to='core.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pro8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro8', to='core.producto'),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
